// <auto-generated />
using FWTL.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FWTL.Database.Migrations
{
    [DbContext(typeof(JobDatabaseContext))]
    [Migration("20181221125132_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FWTL.Core.Entities.Job", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("PeerId");

                    b.Property<int>("PeerType");

                    b.Property<string>("PhoneHashId")
                        .IsRequired();

                    b.Property<int>("State");

                    b.HasKey("Id");

                    b.HasIndex("PhoneHashId");

                    b.ToTable("Job");
                });
#pragma warning restore 612, 618
        }
    }
}
